apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web3-community

bases:
  - ../../base

resources:
  - secrets.yaml
  - ingress.yaml

# dev 이미지 (CI/CD에서 ghcr.io 레지스트리에 push)
images:
  - name: web3-community/api-gateway-service
    newName: ghcr.io/web3-community/api-gateway-service
    newTag: dev
  - name: web3-community/auth-service
    newName: ghcr.io/web3-community/auth-service
    newTag: dev
  - name: web3-community/user-service
    newName: ghcr.io/web3-community/user-service
    newTag: dev
  - name: web3-community/post-service
    newName: ghcr.io/web3-community/post-service
    newTag: dev
  - name: web3-community/comment-service
    newName: ghcr.io/web3-community/comment-service
    newTag: dev

patches:
  - path: patches/app-patch.yaml
  - path: patches/mysql-pvc-patch.yaml
    target:
      kind: StatefulSet
      name: mysql
